#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ]; then
  echo "🔄 Detected merge into main. Running deploy..."
  ./deploy.sh
else
  echo "ℹ️ Merge into $branch detected. No deployment triggered."
fi
