name: Auto Deploy

on:
  push:
    branches:
      - main  # Trigger only on push/merge to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Build project
      - name: Build project
        run: npm run build

      # Step 6: Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 192.168.0.104
          username: 'user'
          key: 'SQVCB5Yjh69TjVTYvqUHSQVAfofMHBhQVExa0bevRuEeF7Th/bbZAYhV7Dh8VuNvNt4EnsHJSV79plmTqHDLzxxS+AQiyBfBYMZo+m7Oq/81bmFEDoTz7uPvbV7O0j+9zkxCWDRSOKnV+TQO8L8ciXs1UAAAEBALsuO0GqZldVqUKbup/19uzm/2qdYKsTQ/C/MK2iOzWRlq3mtMb4Q7cOdSp7NKbSpi93FZ48nD31Ar0YJnohKgwSztsPV5+qg58rKzVSZmtdxxOJQ6AJhWkqUyJdJ6Jukn5z2dS7jPoHWHFC0woW1iZ6Ih65eQbY+ho6I5mQ9UMf2QLDeEj2G3XStrpEdfy2CcNNT26p5V1J6HEwNqEUvUS5LoJ3cdKqco1+7ERRZxyGZr6qXbIY9lNuspPZRCnpG90MDMlG/LoKT9Od2T+9drS3G81pUnV4I1Rv9Y1uBpYwrhekHMk/4MptIpS4YNvMRXIfAovzaHzxPMtxQ7xjwYMAAAAOZ2l0aHViLWFjdGlvbnMBAgMEBQ==-----END OPENSSH PRIVATE KEY-----'
          port: 22
          script: ./deploy.sh
